version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
